CREATE TABLESPACE PERSONA
DATAFILE 'C:\oraclexe\app\oracle\product\11.2.0\server\database\PERSONA.DBF'
SIZE 1M AUTOEXTEND ON NEXT 200K MAXSIZE 1400K
DEFAULT STORAGE (INITIAL 16K NEXT 16K MINEXTENTS 1 MAXEXTENTS 3);

CREATE TABLESPACE CURSO
DATAFILE 'C:\oraclexe\app\oracle\product\11.2.0\server\database\CURSO.DBF'
SIZE 1M AUTOEXTEND ON NEXT 100K MAXSIZE 1500K
DEFAULT STORAGE (INITIAL 16K NEXT 16K MINEXTENTS 1 MAXEXTENTS 3);

CREATE TABLESPACE PROGRAMA
DATAFILE 'C:\oraclexe\app\oracle\product\11.2.0\server\database\PROGRAMA.DBF'
SIZE 1M AUTOEXTEND ON NEXT 100K MAXSIZE 1100K 
DEFAULT STORAGE (INITIAL 16K NEXT 16K MINEXTENTS 1 MAXEXTENTS 3);

CREATE TABLESPACE ESCUELA
DATAFILE 'C:\oraclexe\app\oracle\product\11.2.0\server\database\ESCUELA.DBF'
SIZE 1M AUTOEXTEND ON NEXT 100K MAXSIZE 1100K 
DEFAULT STORAGE (INITIAL 16K NEXT 16K MINEXTENTS 1 MAXEXTENTS 3);

CREATE TABLESPACE CENTRO
DATAFILE 'C:\oraclexe\app\oracle\product\11.2.0\server\database\CENTRO.DBF'
SIZE 1M AUTOEXTEND ON NEXT 100K MAXSIZE 1100K 
DEFAULT STORAGE (INITIAL 16K NEXT 16K MINEXTENTS 1 MAXEXTENTS 3);
